# -*- coding: utf-8 -*-
"""Salah Al-Ratrout

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IkNI2K8WpRjBlGT69sVCCDU9zK59viAS

<h1>Question 5</h1>
"""

try:
    a = int(input())
    b = int(input())

    for i in range(a + 1, b):
        check = True
        for j in range(2, i):
            if i % j == 0:
                check = False
                break
        if check:
            print(i)
except:
    print('Enter an integer')

"""<h1>Question 6</h1>"""

lst1 = [4, 9, 1, 17, 11, 26, 28, 28, 26, 66, 91]
lst2 = [9, 9, 74, 21, 45, 11, 63]
intersect = []
union = []
temp = []

for item1 in lst1:
    if item1 in lst2:
        intersect.append(item1)
    if item1 not in lst2:
        union.append(item1)

for i in range(0, len(lst2)):
    if lst2[i] not in temp:
        temp.append(lst2[i])
union.extend(temp)
    
print(intersect)
print(union)

"""<h1>Question 7</h1>"""

lst = [1, 2, 2, 5, 1, 7, 9, 7, 8, 5, 3]
result = []

for i in range(0, len(lst)):
    if lst[i] not in result:
        result.append(lst[i])
print(result)

"""<h1>Question 8</h1>"""

try:
    a = int(input())
    a = str(a)
    
    res = []

    for i in range(0, len(a)):
        res.append(a[i : i + 1])

    temp = res.copy()
    temp.reverse()

    if res == temp:
        print('Palindrome')
    else:
        print('Not a Palindrome')
        
except:
    print('Enter an integer')

"""<h1>Question 9</h1>"""

lst1 = [4, 9, 1, 17, 11, 26, 28, 28, 26, 66, 91]
lst2 = [9, 9, 74, 21, 45, 11, 63]
intersect = []
union = []


for item1 in lst1:
    if item1 in lst2:
        intersect.append(item1)
    if item1 not in lst2:
        union.append(item1)
union.extend(set(lst2))